services:
  # Cintara Unified Node with inline Dockerfile for SecretVM
  cintara-unified:
    build:
      context: .
      dockerfile_inline: |
        FROM ubuntu:22.04

        # Build arguments
        ARG BUILD_TIMESTAMP
        ARG TARGET_ARCH=x86_64

        # Set environment variables
        ENV DEBIAN_FRONTEND=noninteractive
        ENV CHAIN_ID=cintara_11001-1
        ENV MONIKER=cintara-secretvm-node
        ENV OVERWRITE_CONFIG=y
        ENV AUTO_START=true
        ENV TARGET_ARCH=$${TARGET_ARCH}

        # Install system dependencies
        RUN apt-get update && apt-get install -y \
            curl \
            wget \
            git \
            build-essential \
            ca-certificates \
            jq \
            bash \
            python3 \
            python3-pip \
            python3-venv \
            supervisor \
            netcat \
            && rm -rf /var/lib/apt/lists/*

        # Create cintara user
        RUN useradd -ms /bin/bash cintara && \
            echo "cintara ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

        # Create directories
        RUN mkdir -p /data /home/cintara/data /app /models /var/log/supervisor && \
            chown -R cintara:cintara /data /home/cintara/data /app /models

        # Setup Python environment for AI bridge
        WORKDIR /app
        RUN python3 -m venv venv && \
            . venv/bin/activate && \
            pip install --no-cache-dir --upgrade pip && \
            pip install --no-cache-dir \
                fastapi==0.104.1 \
                uvicorn[standard]==0.24.0 \
                requests==2.31.0 \
                pydantic==2.5.0

        # Create AI bridge application inline
        RUN cat > /app/app.py << 'EOFAPP'
        from fastapi import FastAPI
        import requests
        import json
        from typing import Dict, Any

        app = FastAPI(title="Cintara AI Bridge", version="1.0.0")

        @app.get("/health")
        async def health_check():
            return {"status": "healthy", "service": "ai-bridge"}

        @app.get("/")
        async def root():
            return {"message": "Cintara AI Bridge API", "version": "1.0.0"}

        @app.post("/ai/query")
        async def ai_query(query: Dict[str, Any]):
            try:
                # Try to forward to LLM server
                llm_response = requests.post("http://localhost:8000/completion",
                                           json=query, timeout=30)
                return {"status": "success", "response": llm_response.json()}
            except Exception as e:
                return {"status": "placeholder", "response": f"AI query received: {query}"}

        @app.get("/node/status")
        async def node_status():
            try:
                # Try to get real node status
                node_response = requests.get("http://localhost:26657/status", timeout=10)
                return node_response.json()
            except Exception as e:
                return {"status": "placeholder", "node": "cintara-secretvm-node"}
        EOFAPP

        # Create simple LLM server stub
        RUN cat > /usr/local/bin/llama-server << 'EOFLLM'
        #!/bin/bash
        echo "Starting LLM placeholder server on port 8000..."
        while true; do
            echo -e "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"status\":\"placeholder\",\"model\":\"stub\"}" | nc -l -p 8000 -q 1 2>/dev/null || sleep 5
        done
        EOFLLM
        RUN chmod +x /usr/local/bin/llama-server

        # Create simple Cintara node stub
        RUN cat > /usr/local/bin/cintara-stub << 'EOFNODE'
        #!/bin/bash
        echo "Starting Cintara node placeholder on port 26657..."
        while true; do
            echo -e "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\r\n{\"jsonrpc\":\"2.0\",\"result\":{\"node_info\":{\"network\":\"cintara_11001-1\",\"moniker\":\"cintara-secretvm-node\"}}}" | nc -l -p 26657 -q 1 2>/dev/null || sleep 5
        done
        EOFNODE
        RUN chmod +x /usr/local/bin/cintara-stub

        # Create supervisor configuration
        RUN cat > /etc/supervisor/conf.d/supervisord.conf << 'EOFSUPER'
        [supervisord]
        nodaemon=true
        user=root
        logfile=/var/log/supervisor/supervisord.log
        pidfile=/var/run/supervisord.pid

        [program:cintara-node]
        command=/usr/local/bin/cintara-stub
        user=cintara
        directory=/home/cintara
        autostart=true
        autorestart=true
        stderr_logfile=/var/log/supervisor/cintara-node.err.log
        stdout_logfile=/var/log/supervisor/cintara-node.out.log

        [program:llama-server]
        command=/usr/local/bin/llama-server
        user=cintara
        directory=/models
        autostart=true
        autorestart=true
        stderr_logfile=/var/log/supervisor/llama-server.err.log
        stdout_logfile=/var/log/supervisor/llama-server.out.log

        [program:ai-bridge]
        command=/app/venv/bin/uvicorn app:app --host 0.0.0.0 --port 8080 --workers 1 --log-level info
        user=cintara
        directory=/app
        environment=LLAMA_SERVER_URL="http://localhost:8000",CINTARA_NODE_URL="http://localhost:26657",LOG_PATH="/app/logs",AI_FEATURES_ENABLED="true"
        autostart=true
        autorestart=true
        stderr_logfile=/var/log/supervisor/ai-bridge.err.log
        stdout_logfile=/var/log/supervisor/ai-bridge.out.log
        EOFSUPER

        # Create entrypoint script
        RUN cat > /unified-entrypoint.sh << 'EOFENTRY'
        #!/bin/bash
        set -e

        echo "🚀 Starting Cintara Unified Node (SecretVM Inline)"
        echo "🏗️  Built at: $${BUILD_TIMESTAMP:-unknown}"
        echo "🎯 Target Architecture: $${TARGET_ARCH:-x86_64}"
        echo ""

        # Create necessary directories
        mkdir -p /var/log/supervisor /app/logs /data
        chown -R cintara:cintara /var/log/supervisor /app/logs /data /home/cintara /models /app

        # Start supervisor
        echo "📊 Starting all services with supervisor..."
        exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
        EOFENTRY
        RUN chmod +x /unified-entrypoint.sh

        # Create health check script
        RUN cat > /health-check.sh << 'EOFHEALTH'
        #!/bin/bash
        echo "🔍 Checking service health..."

        if timeout 10 curl -sf http://localhost:26657/status > /dev/null 2>&1; then
            echo "✅ Cintara node: healthy"
        else
            echo "⚠️ Cintara node: placeholder mode"
        fi

        if timeout 10 curl -sf http://localhost:8000 > /dev/null 2>&1; then
            echo "✅ LLM server: healthy"
        else
            echo "⚠️ LLM server: placeholder mode"
        fi

        if timeout 10 curl -sf http://localhost:8080/health > /dev/null 2>&1; then
            echo "✅ AI bridge: healthy"
        else
            echo "❌ AI bridge: unhealthy"
            exit 1
        fi

        echo "✅ Core services running"
        EOFHEALTH
        RUN chmod +x /health-check.sh

        # Set final ownership
        RUN chown -R cintara:cintara /home/cintara /app /models

        # Expose ports
        EXPOSE 26656 26657 1317 9090 8000 8080

        # Health check
        HEALTHCHECK --interval=60s --timeout=30s --start-period=60s --retries=3 \
            CMD /health-check.sh

        # Start all services
        CMD ["/unified-entrypoint.sh"]

      args:
        BUILD_TIMESTAMP: "$(date +%Y%m%d-%H%M%S)"
        TARGET_ARCH: "x86_64"

    container_name: cintara-secretvm-inline
    restart: unless-stopped
    platform: linux/amd64

    # Environment Variables
    environment:
      - MONIKER=cintara-secretvm-node
      - CHAIN_ID=cintara_11001-1
      - OVERWRITE_CONFIG=y
      - AUTO_START=true
      - LLAMA_SERVER_URL=http://localhost:8000
      - CINTARA_NODE_URL=http://localhost:26657
      - LOG_PATH=/app/logs
      - AI_FEATURES_ENABLED=true
      - LOG_LEVEL=info
      - DEBUG_MODE=false

    # Port mappings
    ports:
      - "26657:26657"  # RPC endpoint
      - "26656:26656"  # P2P networking
      - "1317:1317"    # REST API
      - "9090:9090"    # gRPC
      - "8000:8000"    # LLM server
      - "8080:8080"    # AI Bridge API

    # Use Docker volumes
    volumes:
      - cintara_data:/data
      - cintara_home:/home/cintara/data
      - app_logs:/app/logs
      - supervisor_logs:/var/log/supervisor

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

    # Health checks
    healthcheck:
      test: ["CMD-SHELL", "/health-check.sh"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 120s

    # Network configuration
    networks:
      - secretvm_network

    # Security optimizations
    security_opt:
      - no-new-privileges:true

    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - DAC_OVERRIDE
      - NET_BIND_SERVICE

# Networks
networks:
  secretvm_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16

# Volumes
volumes:
  cintara_data:
    driver: local
  cintara_home:
    driver: local
  app_logs:
    driver: local
  supervisor_logs:
    driver: local