services:
  # Unified Cintara Node with LLM and AI Bridge
  cintara-unified:
    build:
      context: .
      dockerfile: Dockerfile.unified
    container_name: cintara-unified-node
    restart: unless-stopped
    environment:
      - CHAIN_ID=cintara_11001-1
      - MONIKER=team-unified-node
      - LLAMA_SERVER_URL=http://localhost:8000
      - CINTARA_NODE_URL=http://localhost:26657
      - LOG_PATH=/app/logs
      - AI_FEATURES_ENABLED=true
    ports:
      # Cintara node ports
      - "26657:26657"  # RPC
      - "26656:26656"  # P2P
      - "1317:1317"    # REST API
      - "9090:9090"    # gRPC
      # LLM server port
      - "8000:8000"    # LLM API
      # AI bridge port
      - "8080:8080"    # AI Bridge API
    volumes:
      - cintara_data:/data
      - cintara_home:/home/cintara/data
      - model_cache:/models
      - bridge_logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 6G
        reservations:
          cpus: '2.0'
          memory: 4G
    healthcheck:
      test: ["CMD-SHELL", "/health-check.sh"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 180s

# Networks (optional, but good practice)
networks:
  default:
    driver: bridge

# Volumes for persistent data
volumes:
  cintara_data:
    driver: local
  cintara_home:
    driver: local
  model_cache:
    driver: local
  bridge_logs:
    driver: local