version: '3.8'

services:
  cintara-unified-node:
    # Pre-configured unified image containing ALL services:
    # 1. Cintara Blockchain Node (cintarad) - Port 26657
    # 2. AI Bridge FastAPI Service - Port 8080
    # 3. LLM Server Stub - Port 8000
    # All managed by supervisor within single container
    image: public.ecr.aws/b8j2u1c6/cintaraio/cintara-secretvm-ready:latest
    container_name: cintara-unified-node
    restart: unless-stopped

    # No environment variables needed - everything is pre-configured!
    # Services start automatically via supervisor

    # Port mappings for all internal services
    ports:
      # Cintara Blockchain Node ports
      - "26656:26656"  # P2P port for peer connections
      - "26657:26657"  # RPC port for API calls (main endpoint)
      - "1317:1317"    # REST API port
      - "9090:9090"    # gRPC port

      # AI Services ports
      - "8000:8000"    # LLM Server (tinyllama stub)
      - "8080:8080"    # AI Bridge FastAPI (connects LLM + blockchain)

    # Persistent data storage
    volumes:
      - cintara_secretvm_data:/data
      - cintara_secretvm_logs:/var/log/supervisor

    # Health check (verifies all services are running)
    healthcheck:
      # Primary: Check blockchain node
      test: ["CMD", "curl", "-f", "http://localhost:26657/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

    # Additional service verification (manual):
    # - LLM Server: curl http://localhost:8000
    # - AI Bridge: curl http://localhost:8080/health

    # Resource limits for SecretVM
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

# Persistent volumes
volumes:
  cintara_secretvm_data:
    driver: local
  cintara_secretvm_logs:
    driver: local