version: '3.8'

services:
  cintara-secretvm-node:
    # Use the working pre-configured image from ECR
    image: public.ecr.aws/b8j2u1c6/cintaraio/cintara-secretvm-ready:latest
    container_name: cintara-secretvm-node
    restart: unless-stopped

    # No environment variables needed - everything is pre-configured!

    # Port mappings
    ports:
      - "26656:26656"  # P2P port for peer connections
      - "26657:26657"  # RPC port for API calls
      - "1317:1317"    # REST API port
      - "9090:9090"    # gRPC port
      - "8000:8000"    # LLM server
      - "8080:8080"    # AI bridge API

    # Persistent data storage
    volumes:
      - cintara_secretvm_data:/data
      - cintara_secretvm_logs:/var/log/supervisor

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:26657/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

    # Resource limits for SecretVM
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

# Persistent volumes
volumes:
  cintara_secretvm_data:
    driver: local
  cintara_secretvm_logs:
    driver: local