version: '3.8'

services:
  cintara-secret-unified:
    build:
      context: .
      dockerfile: Dockerfile.secret
    container_name: cintara-secret-node
    restart: unless-stopped
    environment:
      # Secret Network Configuration
      - MONIKER=cintara-secret-node
      - CHAIN_ID=secret-4
      - GENESIS_URL=https://github.com/scrtlabs/SecretNetwork/releases/latest/download/genesis.json
      - PERSISTENT_PEERS=bee0edb320d50c1bcb6bd59b4e04456d459bd70e@secret-4.node.enigma.co:26656,4ca26a20aaa042d0073ad4b685ef5b4c3e4a0e6d@secret-4.node.enigma.co:26656

      # Service Configuration
      - LLAMA_SERVER_URL=http://localhost:8000
      - CINTARA_NODE_URL=http://localhost:26657
      - LOG_LEVEL=info
      - AI_FEATURES_ENABLED=true

    ports:
      # Cintara/Secret node ports
      - "26657:26657"  # RPC endpoint
      - "26656:26656"  # P2P networking
      - "1317:1317"    # REST API
      - "9090:9090"    # gRPC

      # LLM server port
      - "8000:8000"    # LLaMA.cpp server

      # AI bridge port
      - "8080:8080"    # FastAPI AI bridge

    volumes:
      # Persistent data storage for Secret Network node
      - secret_node_data:/home/cintara/.secretd
      - secret_models:/models
      - secret_logs:/app/logs
      - supervisor_logs:/var/log/supervisor

    deploy:
      resources:
        limits:
          cpus: '6.0'
          memory: 8G
        reservations:
          cpus: '4.0'
          memory: 6G

    healthcheck:
      test: ["CMD-SHELL", "/app/health-check.sh"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 600s  # 10 minutes for Secret Network sync

    networks:
      - secret-network

# Dedicated network for Secret Network deployment
networks:
  secret-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Persistent volumes for Secret Network data
volumes:
  secret_node_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/secret-node-data  # Host path for node data

  secret_models:
    driver: local

  secret_logs:
    driver: local

  supervisor_logs:
    driver: local