services:
  # Fully Automated Cintara Node with LLM and AI Bridge
  cintara-unified:
    # Use pre-built image from ECR
    image: public.ecr.aws/b8j2u1c6/cintaraio/cintara-unified:latest

    # Alternative: Build unified image with all components locally
    # build:
    #   context: .
    #   dockerfile: Dockerfile.unified
    container_name: cintara-unified-automated
    restart: unless-stopped
    environment:
      # Node Configuration (these can be customized)
      - MONIKER=cintara-automated-node
      - CHAIN_ID=cintara_11001-1
      - OVERWRITE_CONFIG=y
      - AUTO_START=true
      # Service URLs
      - LLAMA_SERVER_URL=http://localhost:8000
      - CINTARA_NODE_URL=http://localhost:26657
      - LOG_PATH=/app/logs
      - AI_FEATURES_ENABLED=true
      # Logging
      - LOG_LEVEL=info
    ports:
      # Cintara node ports
      - "26657:26657"  # RPC
      - "26656:26656"  # P2P
      - "1317:1317"    # REST API
      - "9090:9090"    # gRPC
      # LLM server port
      - "8000:8000"    # LLM API
      # AI bridge port
      - "8080:8080"    # AI Bridge API
    volumes:
      - cintara_data:/data
      - cintara_home:/home/cintara/data
      - model_cache:/models
      - bridge_logs:/app/logs
      - supervisor_logs:/var/log/supervisor
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 6G
        reservations:
          cpus: '2.0'
          memory: 4G
    healthcheck:
      test: ["CMD-SHELL", "/health-check.sh"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 300s  # 5 minutes for full startup

# Networks
networks:
  default:
    driver: bridge

# Volumes for persistent data
volumes:
  cintara_data:
    driver: local
  cintara_home:
    driver: local
  model_cache:
    driver: local
  bridge_logs:
    driver: local
  supervisor_logs:
    driver: local