FROM ubuntu:22.04

RUN apt-get update && apt-get install -y curl jq bash wget unzip build-essential git sudo

RUN useradd -ms /bin/bash cintara && echo "cintara ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER cintara
WORKDIR /home/cintara

# Clone the official cintara testnet script
RUN git clone https://github.com/Cintaraio/cintara-testnet-script.git

WORKDIR /home/cintara/cintara-testnet-script

CMD ["bash"]