version: '3.8'

# SecretVM-Compatible Docker Compose Configuration
# This file follows SecretVM best practices for verifiable and secure deployment
# Requirements: Intel x86 with SGX/TDX or AMD with SEV (NO Apple M1/M2 support)

services:
  # Unified Cintara Node with LLM and AI Bridge for SecretVM
  cintara-unified:
    # For testing: Build from source with pinned versions for reproducibility
    build:
      context: .
      dockerfile: Dockerfile.secretvm

    # Production: Use exact image with SHA256 hash for verifiability (SecretVM best practice)
    # image: public.ecr.aws/b8j2u1c6/cintaraio/cintara-unified:latest@sha256:ACTUAL_HASH_HERE

    container_name: cintara-secretvm-unified
    restart: unless-stopped

    # SecretVM Environment Variables (can be injected as secrets via SecretVM portal)
    environment:
      # Node Configuration
      - MONIKER=cintara-secretvm-node
      - CHAIN_ID=cintara_11001-1
      - OVERWRITE_CONFIG=y
      - AUTO_START=true

      # Service URLs (internal networking)
      - LLAMA_SERVER_URL=http://localhost:8000
      - CINTARA_NODE_URL=http://localhost:26657
      - LOG_PATH=/app/logs
      - AI_FEATURES_ENABLED=true

      # Security and Logging
      - LOG_LEVEL=info
      - SECURE_MODE=true
      - TEE_ATTESTATION=enabled

      # SecretVM-specific configurations
      - SECRETVM_MODE=true
      - CONFIDENTIAL_COMPUTING=enabled

    # Port mappings for SecretVM
    ports:
      # Cintara blockchain node ports
      - "26657:26657"  # RPC (can be restricted in SecretVM)
      - "26656:26656"  # P2P
      - "1317:1317"    # REST API
      - "9090:9090"    # gRPC

      # AI/LLM services
      - "8000:8000"    # LLM API (internal)
      - "8080:8080"    # AI Bridge API (main interface)

      # Optional: Attestation endpoint
      - "9999:9999"    # TEE Attestation endpoint

    # Persistent volumes for blockchain data
    volumes:
      - cintara_secretvm_data:/data
      - cintara_secretvm_home:/home/cintara/data
      - model_cache_secretvm:/models
      - bridge_logs_secretvm:/app/logs
      - supervisor_logs_secretvm:/var/log/supervisor
      - attestation_data:/attestation  # SecretVM attestation data

    # Resource constraints for SecretVM environment
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 6G
        reservations:
          cpus: '2.0'
          memory: 4G

    # Enhanced health checks for SecretVM
    healthcheck:
      test: |
        /bin/bash -c '
          # Check all services
          curl -sf http://localhost:26657/status > /dev/null &&
          curl -sf http://localhost:8000/health > /dev/null &&
          curl -sf http://localhost:8080/health > /dev/null &&
          # Verify TEE attestation (if enabled)
          curl -sf http://localhost:9999/attestation > /dev/null || true
        '
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 300s  # Allow extra time for SecretVM initialization

    # Security configurations for TEE environment
    security_opt:
      - no-new-privileges:true

    # Capabilities (minimal for security)
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - DAC_OVERRIDE

    # User namespace (for enhanced security)
    user: "1001:1001"

    # Tmpfs mounts for sensitive temporary data
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
      - /var/tmp:rw,noexec,nosuid,size=50m

# Networks for SecretVM isolation
networks:
  secretvm_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: secretvm-br0
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Persistent volumes for SecretVM deployment
volumes:
  cintara_secretvm_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/secretvm/cintara

  cintara_secretvm_home:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/secretvm/home

  model_cache_secretvm:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/secretvm/models

  bridge_logs_secretvm:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/secretvm/logs

  supervisor_logs_secretvm:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/secretvm/supervisor

  attestation_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/secretvm/attestation

# SecretVM-specific configurations
x-secretvm-config:
  # Attestation configuration
  attestation:
    enabled: true
    endpoint: "http://localhost:9999/attestation"
    verify_chain: true

  # Reproducible build information
  build_info:
    git_commit: "${GIT_COMMIT:-unknown}"
    build_timestamp: "${BUILD_TIMESTAMP:-unknown}"
    dockerfile_hash: "${DOCKERFILE_HASH:-unknown}"

  # TEE specifications
  tee_requirements:
    intel_sgx: ">=2.0"
    intel_tdx: ">=1.0"
    amd_sev: ">=1.0"

  # Security policies
  security:
    encrypted_storage: true
    secure_boot: required
    code_integrity: enforced
    remote_attestation: required