services:
  # Simplified Cintara Unified Node for SecretVM
  cintara-simple:
    # Build from simple Dockerfile
    build:
      context: .
      dockerfile: Dockerfile.secretvm-simple
      args:
        BUILD_TIMESTAMP: "${BUILD_TIMESTAMP:-$(date +%Y%m%d-%H%M%S)}"
        TARGET_ARCH: "x86_64"

    container_name: cintara-secretvm-simple
    restart: unless-stopped
    platform: linux/amd64

    # Environment Variables
    environment:
      - MONIKER=cintara-secretvm-node
      - CHAIN_ID=cintara_11001-1
      - OVERWRITE_CONFIG=y
      - AUTO_START=true

      # Service URLs
      - LLAMA_SERVER_URL=http://localhost:8000
      - CINTARA_NODE_URL=http://localhost:26657
      - LOG_PATH=/app/logs
      - AI_FEATURES_ENABLED=true

      # Logging
      - LOG_LEVEL=info
      - DEBUG_MODE=false

    # Port mappings
    ports:
      # Cintara blockchain node
      - "26657:26657"  # RPC endpoint
      - "26656:26656"  # P2P networking
      - "1317:1317"    # REST API
      - "9090:9090"    # gRPC

      # AI/LLM services
      - "8000:8000"    # LLM server
      - "8080:8080"    # AI Bridge API

    # Use Docker volumes
    volumes:
      - cintara_data:/data
      - cintara_home:/home/cintara/data
      - app_logs:/app/logs
      - supervisor_logs:/var/log/supervisor

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

    # Simplified health checks
    healthcheck:
      test: [
        "CMD-SHELL",
        "/health-check.sh"
      ]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 120s  # 2 minutes for startup

    # Network configuration
    networks:
      - secretvm_network

    # Security optimizations
    security_opt:
      - no-new-privileges:true

    # Minimal capabilities
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - DAC_OVERRIDE
      - NET_BIND_SERVICE

# Networks
networks:
  secretvm_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16

# Volumes
volumes:
  cintara_data:
    driver: local

  cintara_home:
    driver: local

  app_logs:
    driver: local

  supervisor_logs:
    driver: local