services:
  cintara-node-simple:
    build:
      context: .
      dockerfile: Dockerfile.simple
    image: cintara-node-simple:local
    container_name: cintara-node-simple
    platform: linux/amd64
    volumes:
      - ./data:/data
    ports:
      - "26656:26656"
      - "26657:26657"
    stdin_open: true
    tty: true
    command: bash

  llama:
    image: ${LLAMA_REPO}@${LLAMA_DIGEST}
    command: [
      "--model","/models/${MODEL_FILE}",
      "--ctx-size","${CTX_SIZE}",
      "--threads","${LLM_THREADS}",
      "--host","0.0.0.0",
      "--port","8000"
    ]
    volumes:
      - ./models:/models:ro
    expose: ["8000"]

  bridge:
    build: ./bridge
    environment:
      - LLAMA_SERVER_URL=http://llama:8000
      - CINTARA_NODE_URL=http://cintara-node-simple:26657
      - LOG_PATH=/shared/logs
    volumes:
      - ./data:/shared:ro
    depends_on:
      - llama
    ports:
      - "8080:8080"